steps:
  # Build the container image
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/$PROJECT_ID/humanoid-robot-repo/humanoid-robot-simulator:$COMMIT_SHA",
        ".",
      ]

  # Push the container image to Artifact Registry
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/$PROJECT_ID/humanoid-robot-repo/humanoid-robot-simulator:$COMMIT_SHA",
      ]

  # Deploy container image to Cloud Run
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk"
    entrypoint: gcloud
    args:
      - "run"
      - "deploy"
      - "humanoid-robot-simulator"
      - "--image"
      - "us-central1-docker.pkg.dev/$PROJECT_ID/humanoid-robot-repo/humanoid-robot-simulator:$COMMIT_SHA"
      - "--region"
      - "us-central1"
      - "--platform"
      - "managed"
      - "--allow-unauthenticated"
      - "--port"
      - "5000"
      - "--memory"
      - "1Gi"
      - "--cpu"
      - "1"
      - "--max-instances"
      - "10"
      - "--min-instances"
      - "0"
      - "--timeout"
      - "3600"
      - "--concurrency"
      - "80"

images:
  - "us-central1-docker.pkg.dev/$PROJECT_ID/humanoid-robot-repo/humanoid-robot-simulator:$COMMIT_SHA"
