apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: humanoid-robot-simulator
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/ingress-status: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 80
      timeoutSeconds: 3600
      containers:
        - image: gcr.io/PROJECT_ID/humanoid-robot-simulator:latest
          ports:
            - name: http1
              containerPort: 5000
          env:
            - name: PORT
              value: "5000"
            - name: FLASK_ENV
              value: "production"
          resources:
            limits:
              cpu: 1000m
              memory: 1Gi
          startupProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 10
            timeoutSeconds: 5
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 5
          livenessProbe:
            httpGet:
              path: /
              port: 5000
            initialDelaySeconds: 30
            timeoutSeconds: 5
            periodSeconds: 30
            successThreshold: 1
            failureThreshold: 3
  traffic:
    - percent: 100
      latestRevision: true
